# Site settings
title: Ecole de Formation Pizzaïolo
email: contact@alexchopin.com
description: "Ecole de formation au métier de pizzaïolo située dans les Hautes-pyrénées à Lannemezan. Formations animés par Jean-Jacques Despaux maître artisan et maître pizzaiolo instructeur."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: ""
github_username:  ""
include: ['_pages']
# Build settings
markdown: kramdown
sass:
    style: compressed
